alter table BAKERIES_COMPONENT add constraint FK_BAKERIES_COMPONENT_ON_BAKERY foreign key (BAKERY_ID) references BAKERIES_BAKERY(ID);
create unique index IDX_BAKERIES_COMPONENT_UK_NAME on BAKERIES_COMPONENT (NAME) where DELETE_TS is null ;
create index IDX_BAKERIES_COMPONENT_ON_BAKERY on BAKERIES_COMPONENT (BAKERY_ID);
